steps:

    # --- IGNORE 
  - remove: .vs/

    # --- SET VARIABLES
  - read: owner_name
    from: env.owner_name
    fallback:
      from: git.author_name


  - read: owner_email
    from: env.owner_email
    fallback:
      from: git.author_email

  - read: repo_name
    from: env.repo_name
    fallback:
      from: git.remote_name
      fallback:
        from: filesystem.rootdir

  - read: repo_desc
    from: env.repo_desc
 
  - read: repo_url
    from: env.repo_url
    fallback:
      from: git.remote_url
      fallback:
        eval: 'git@github.com/{{ owner_name }}/{{ repo_name }}.git'
        
  - read: now
    eval: '{{ datetime.now | datetime format: DD, MMMM Y}}'
    
  - read: namespace
    from: env.namespace
    fallback:
      eval: '{{ repo_name }}'

    # --- GENERATE FILES
  - copy: template/cpp/cmake/**/*
    to: cmake/
  
  - copy: template/README.md
    to: README.md

  - copy: template/cpp/main.hpp
    to: 'include/{{ repo_name | lowercase }}/{{ repo_name | lowercase }}.hpp'
  - copy: template/cpp/main.cpp
    to: 'src/{{ repo_name | lowercase }}.cpp'
    
  - copy: template/cpp/CMakeLists.txt
    to: './CMakeLists.txt'

    # For benchmarks
  - copy: template/cpp/benchmarks/**/*
    to: benchmarks/
    
    # For tests
  - copy: template/cpp/tests/**/*
    to: tests/
  - copy: tests/lib.cpp
    to: tests/{{ repo_name | lowercase }}.cpp
  - remove: tests/lib.cpp

    # For examples
  - copy: template/cpp/examples/**/*
    to: examples/

    # For benchmarks
  - copy: template/.github/**/*
    to: .github/

   
    # --- CLEAN
  - remove: docs/pages/reference.md
  - remove: template/
  - remove: LICENSE.txt
  - remove: .tmplr.yml