steps:

    # --- SET VARIABLES
  - read: owner_name
    from: env.owner_name
    fallback:
      from: git.author_name
      fallback:
        prompt: What is your name ?


  - read: owner_email
    from: env.owner_email
    fallback:
      from: git.author_email
      fallback:
        prompt: What is your email address ?

  - read: repo_name
    from: env.repo_name
    fallback:
      from: git.remote_name
      fallback:
        from: filesystem.rootdir

  - read: repo_desc
    from: env.repo_desc
    fallback:
      prompt: What is the short description of your project ?
 
  - read: repo_url
    from: env.repo_url
    fallback:
      from: git.remote_url
      fallback:
        eval: 'git@github.com/{{ owner_name }}/{{ repo_name }}.git'
        
  - read: now
    eval: '{{ datetime.now | datetime format: dddd, MMMM Y}}'
    
  - read: namespace
    from: env.namespace
    fallback:
      prompt: What is the namespace of your library ?
      default: 
        eval: '{{ repo_name }}'

    # --- GENERATE FILES
  - update: cmake/utility.cmake
  - update: cmake/tools.cmake
  
  - copy: template/README.md
    to: README.md

  - copy: template/static_library/main.hpp
    to: 'include/{{ repo_name | lowercase }}/{{ repo_name | lowercase }}.hpp'
  - copy: template/static_library/main.cpp
    to: 'src/{{ repo_name | lowercase }}.cpp'
    
  - copy: template/static_library/CMakeLists.txt
    to: './CMakeLists.txt'

    # For benchmarks
  - update: benchmarks/CMakeLists.txt
    
    # For tests
  - update: tests/lib.cpp
  - copy: tests/lib.cpp
    to: './tests/{{ repo_name | lowercase }}.cpp'
  - remove: tests/lib.cpp

  - update: tests/CMakeLists.txt

   
    # --- CLEAN
  - remove: template/
  - remove: LICENSE.txt
  - remove: .tmplr.yml