DOXYFILE    = 'Doxyfile'
FINE_PRINT  = "<p><b><a href=\"@PROJECT_HOMEPAGE_URL@\">@PROJECT_NAME@</a></b> - @PROJECT_DESCRIPTION@<br />Generated by <a href=\"https://doxygen.org/\">Doxygen</a> {doxygen_version} and <a href=\"https://mcss.mosra.cz/\">m.css</a>.</p"

# Add your own navbar links using the code below.
# To find the valid link names, you can inspect the URL of a generated documentation site.
# See : https://mcss.mosra.cz/documentation/doxygen/#navbar-links

LINKS_NAVBAR1 = [
  ("Pages", 'pages', []),
  ("Namespaces", 'namespaces', [])
]

LINKS_NAVBAR2 = [
    ("<a href=\"@PROJECT_HOMEPAGE_URL@\">GitHub</a>", []),
    (None, 'files', [])
]

# LINKS_NAVBAR2 = [
#     ("Classes", 'annotated', []),
#     ("Files", 'files', [])
# ]
