# Reusable worflow to execute tests on different oses
on:
  workflow_call:
    inputs:
      cpm_source_cache:
        required: false 
        default: ${{github.workspace}}/.cpm_cache
        type: string
      os:
        required: true
        type: string
      architecture:
        required: true
        type: string
      toolchain:
        required: true
        type: string
      configuration:
        required: true
        type: string

env:
    CPM_SOURCE_CACHE: ${{inputs.cpm_source_cache}}

jobs:
  setup:
    uses: ./.github/workflows/0_setup_workflow.yaml
    with:
        cpm_source_cache: ${{inputs.cpm_source_cache}}
        os: ${{inputs.os}}
        architecture: ${{inputs.architecture}}
        configuration: ${{inputs.configuration}}
        toolchain: ${{inputs.toolchain}}

  build:
    runs-on: ${{inputs.os}}
    needs: setup
    steps:
    - name: Build
      run: |
          cmake --preset ${{ needs.setup.outputs.preset_name }}
          cmake --build ${{ needs.setup.outputs.build_directory }} --target tests

    - name: Run tests
      working-directory: ${{ needs.setup.outputs.build_directory }}
      run: |
          ctest