name: "Ubuntu & MacOS [Clang & GCC]"

on:
  push:
    branches: ["master"]
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/ubuntu.yaml'
  pull_request:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/ubuntu.yaml'

jobs:
  build:
    if: github.repository != 'TBlauwe/cpp_lib_starter'
    name: "[${{matrix.os}}] : ${{matrix.architecture}}-${{matrix.configuration}}-${{matrix.toolchain}}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        architecture: [x64]
        configuration: [release]
        toolchain: [clang, gnu]

    env:
        preset_name: ${{matrix.architecture}}-${{matrix.configuration}}-${{matrix.toolchain}} 
        build_directory: ./out/build/${{matrix.architecture}}-${{matrix.configuration}}-${{matrix.toolchain}} 
        CPM_SOURCE_CACHE: ${{github.workspace}}/.cpm_cache

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: 'CMakeLists.txt'

    - name: "Cache CPM dependencies" 
      uses: actions/cache@v3
      if: steps.check_files.outputs.files_exists == 'true'
      with:
        path: ${{ env.CPM_SOURCE_CACHE }}
        key: cpm-${{ hashFiles('**/*.cmake', '**/CMakeLists.txt') }}
        enableCrossOsArchive: true

    # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
    - name: "Install CMake and Ninja"
      if: steps.check_files.outputs.files_exists == 'true'
      uses: lukka/get-cmake@latest

    - name: Build
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
          cmake --preset ${{ env.preset_name }}
          cmake --build ${{ env.build_directory }} --target tests

    - name: Run tests
      if: steps.check_files.outputs.files_exists == 'true'
      working-directory: ${{ env.build_directory }}
      run: |
          ctest
