name: "Windows [Clang-cl & MSVC]"

on:
  push:
    branches: ["master"]
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/windows.yaml'
  pull_request:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/windows.yaml'

jobs:
  build:
    name: "[${{matrix.os}}] : ${{matrix.architecture}}-${{matrix.configuration}}-${{matrix.toolchain}}"

    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x64]
        configuration: [release]
        toolchain: [clang-cl, msvc]

    runs-on: ${{ matrix.os }}

    env:
        preset_name: ${{matrix.architecture}}-${{matrix.configuration}}-${{matrix.toolchain}} 
        build_directory: ./out/build/${{matrix.architecture}}-${{matrix.configuration}}-${{matrix.toolchain}} 
        CPM_SOURCE_CACHE: ${{github.workspace}}/.cpm_cache

    steps:
    - uses: actions/checkout@v3

    - name: "Cache CPM dependencies" 
      uses: actions/cache@v3
      with:
        path: ${{ env.CPM_SOURCE_CACHE }}
        key: cpm-${{ hashFiles('**/*.cmake', '**/CMakeLists.txt') }}

    # Configure Developer Command Prompt for Microsoft Visual C++.
    - uses: ilammy/msvc-dev-cmd@v1

    # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
    - uses: lukka/get-cmake@latest

    - name: Build
      run: |
          cmake --preset ${{ env.preset_name }}
          cmake --build ${{ env.build_directory }} --target tests

    - name: Run tests
      working-directory: ${{ env.build_directory }}
      run: |
          ctest
